"""Blueprint ORM model.

The centrepiece of Archon's output — a complete AI architecture blueprint
generated from a user query. Contains the workflow graph (as JSON), a
human-readable diagram, model recommendations, cost/latency estimates with
benchmark citations, the LLM explanation, and the RAGAs eval score.
"""

from __future__ import annotations

import uuid
from typing import Any

from sqlalchemy import Float, ForeignKey, String, Text
from sqlalchemy import JSON as JSONB, Uuid as UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base


class Blueprint(Base):
    """Complete AI stack blueprint generated by the Archon pipeline."""

    __tablename__ = "blueprints"

    query_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("queries.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        doc="Source query that triggered this blueprint.",
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        doc="Owner of this blueprint.",
    )
    architecture_json: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False,
        doc="Full workflow graph: input → router → models → tools → output.",
    )
    architecture_diagram: Mapped[str | None] = mapped_column(
        Text, nullable=True,
        doc="Human-readable diagram in Mermaid syntax.",
    )
    model_recommendations: Mapped[list[dict[str, Any]]] = mapped_column(
        JSONB, nullable=False, default=list, server_default="[]",
        doc="Ranked list of model recommendations with scores.",
    )
    cost_estimate: Mapped[dict[str, Any] | None] = mapped_column(
        JSONB, nullable=True,
        doc="Estimated monthly cost breakdown by model and usage tier.",
    )
    latency_estimate: Mapped[dict[str, Any] | None] = mapped_column(
        JSONB, nullable=True,
        doc="Estimated p95 latency per pipeline step (ms).",
    )
    explanation: Mapped[str | None] = mapped_column(
        Text, nullable=True,
        doc="Plain-English explanation of why this stack was recommended.",
    )
    benchmark_citations: Mapped[list[dict[str, Any]]] = mapped_column(
        JSONB, nullable=False, default=list, server_default="[]",
        doc="List of benchmark sources cited in cost/latency estimates.",
    )
    eval_score: Mapped[float | None] = mapped_column(
        Float, nullable=True,
        doc="Composite RAGAs score (0.0–1.0).",
    )
    eval_details: Mapped[dict[str, Any] | None] = mapped_column(
        JSONB, nullable=True,
        doc="Per-metric RAGAs breakdown (faithfulness, relevancy, precision, recall).",
    )
    confidence_flag: Mapped[str] = mapped_column(
        String(20), nullable=False, default="normal", server_default="normal",
        doc="'normal' or 'low_confidence' if eval score < threshold.",
    )
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, default="draft", server_default="draft",
        index=True,
        doc="Blueprint lifecycle: draft → final → archived.",
    )

    # ── Relationships ────────────────────────────────────────────
    query = relationship("Query", back_populates="blueprints")
    user = relationship("User", back_populates="blueprints")
    eval_results = relationship("EvalResult", back_populates="blueprint", lazy="selectin")

    def __repr__(self) -> str:
        return f"<Blueprint id={self.id!s:.8} status={self.status} eval={self.eval_score}>"
