import { useState } from 'react';
import { Download, Loader2, FileJson } from 'lucide-react';

interface DownloadButtonProps {
  blueprintData: any;
  inputText: string;
}

export default function DownloadButton({ blueprintData, inputText }: DownloadButtonProps) {
  const [loadingPdf, setLoadingPdf] = useState(false);

  const downloadJson = () => {
    const blob = new Blob([JSON.stringify(blueprintData, null, 2)], {
      type: 'application/json',
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `archon-blueprint-${Date.now()}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const downloadPdf = async () => {
    setLoadingPdf(true);
    try {
      const { jsPDF } = await import('jspdf');
      const doc = new jsPDF({ unit: 'mm', format: 'a4' });

      const margin = 15;
      let y = margin;
      const pageW = doc.internal.pageSize.getWidth();
      const maxW = pageW - margin * 2;

      // Header — violet on white
      doc.setFillColor(91, 0, 232);
      doc.rect(0, 0, pageW, 32, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(18);
      doc.setFont('helvetica', 'bold');
      doc.text('Archon — AI Architecture Blueprint', margin, 21);
      y = 42;

      // Input
      doc.setTextColor(91, 0, 232);
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.text('PRODUCT IDEA', margin, y);
      y += 6;
      doc.setTextColor(40, 40, 40);
      doc.setFontSize(11);
      doc.setFont('helvetica', 'normal');
      const inputLines = doc.splitTextToSize(inputText, maxW);
      doc.text(inputLines, margin, y);
      y += inputLines.length * 6 + 8;

      // Detected Tasks
      if (blueprintData.detected_tasks?.length) {
        doc.setTextColor(91, 0, 232);
        doc.setFontSize(9);
        doc.setFont('helvetica', 'bold');
        doc.text('DETECTED AI TASKS', margin, y);
        y += 6;
        doc.setTextColor(40, 40, 40);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);
        blueprintData.detected_tasks.forEach((t: any) => {
          doc.text(`• ${t.task} (confidence: ${(t.confidence * 100).toFixed(0)}%)`, margin + 4, y);
          y += 6;
        });
        y += 4;
      }

      // Models
      if (blueprintData.recommendations?.length) {
        doc.setTextColor(91, 0, 232);
        doc.setFontSize(9);
        doc.setFont('helvetica', 'bold');
        doc.text('RECOMMENDED MODELS', margin, y);
        y += 6;
        blueprintData.recommendations.slice(0, 5).forEach((r: any, i: number) => {
          doc.setTextColor(40, 40, 40);
          doc.setFont('helvetica', 'normal');
          doc.setFontSize(10);
          doc.text(
            `${i + 1}. ${r.model_name} (${r.provider}) — score: ${r.scores?.composite?.toFixed(2) ?? 'N/A'}`,
            margin + 4, y
          );
          y += 6;
        });
        y += 4;
      }

      // Cost
      if (blueprintData.cost_estimate) {
        doc.setTextColor(91, 0, 232);
        doc.setFontSize(9);
        doc.setFont('helvetica', 'bold');
        doc.text('COST ESTIMATE', margin, y);
        y += 6;
        doc.setTextColor(40, 40, 40);
        doc.setFontSize(11);
        doc.setFont('helvetica', 'bold');
        doc.text(
          `Total Monthly: $${blueprintData.cost_estimate.total_monthly_usd?.toFixed(2) ?? '—'}`,
          margin + 4, y
        );
        y += 8;
        doc.setFont('helvetica', 'normal');
      }

      // Latency
      if (blueprintData.latency_estimate) {
        doc.setTextColor(91, 0, 232);
        doc.setFontSize(9);
        doc.setFont('helvetica', 'bold');
        doc.text('LATENCY ESTIMATE', margin, y);
        y += 6;
        doc.setTextColor(40, 40, 40);
        doc.setFontSize(11);
        doc.setFont('helvetica', 'bold');
        doc.text(
          `Total P95: ${blueprintData.latency_estimate.total_p95_ms ?? '—'}ms`,
          margin + 4, y
        );
        y += 8;
        doc.setFont('helvetica', 'normal');
      }

      // Explanation
      if (blueprintData.explanation) {
        if (y > 220) { doc.addPage(); y = margin; }
        doc.setTextColor(91, 0, 232);
        doc.setFontSize(9);
        doc.setFont('helvetica', 'bold');
        doc.text('ARCHITECTURE EXPLANATION', margin, y);
        y += 6;
        doc.setTextColor(40, 40, 40);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9);
        const expLines = doc.splitTextToSize(blueprintData.explanation, maxW);
        doc.text(expLines, margin, y);
      }

      // Footer
      const pageCount = (doc.internal as any).getNumberOfPages();
      for (let p = 1; p <= pageCount; p++) {
        doc.setPage(p);
        doc.setTextColor(160, 160, 160);
        doc.setFontSize(8);
        doc.text(
          `Generated by Archon | ${new Date().toLocaleDateString()} | Page ${p}/${pageCount}`,
          pageW / 2, doc.internal.pageSize.getHeight() - 8,
          { align: 'center' }
        );
      }

      doc.save(`archon-blueprint-${Date.now()}.pdf`);
    } catch (e) {
      console.error('PDF generation failed', e);
    } finally {
      setLoadingPdf(false);
    }
  };

  return (
    <div className="flex items-center gap-3">
      <button
        onClick={downloadJson}
        className="flex items-center gap-2 h-9 px-4 rounded-xl text-[13px] font-semibold transition-all"
        style={{
          background: 'white',
          border: '1.5px solid rgba(91,0,232,0.2)',
          color: '#374151',
          boxShadow: '0 1px 4px rgba(0,0,0,0.06)',
        }}
        onMouseEnter={e => { (e.currentTarget as HTMLButtonElement).style.borderColor = '#5B00E8'; (e.currentTarget as HTMLButtonElement).style.color = '#5B00E8'; }}
        onMouseLeave={e => { (e.currentTarget as HTMLButtonElement).style.borderColor = 'rgba(91,0,232,0.2)'; (e.currentTarget as HTMLButtonElement).style.color = '#374151'; }}
      >
        <FileJson className="w-4 h-4" />
        Export JSON
      </button>

      <button
        onClick={downloadPdf}
        disabled={loadingPdf}
        className="flex items-center gap-2 h-9 px-4 rounded-xl text-[13px] font-semibold transition-all disabled:opacity-60"
        style={{
          background: '#5B00E8',
          border: '1.5px solid #5B00E8',
          color: '#fff',
          boxShadow: '0 2px 12px rgba(91,0,232,0.35)',
        }}
        onMouseEnter={e => { (e.currentTarget as HTMLButtonElement).style.background = '#4800BA'; }}
        onMouseLeave={e => { (e.currentTarget as HTMLButtonElement).style.background = '#5B00E8'; }}
      >
        {loadingPdf ? (
          <Loader2 className="w-4 h-4 animate-spin" />
        ) : (
          <Download className="w-4 h-4" />
        )}
        Export PDF
      </button>
    </div>
  );
}
